services:
  - type: web
    name: Dino Rally Rush
    env: static
    buildCommand: echo "No build command needed for static files"
    staticPublishPath: .
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html